### ISSUE TITLE
Opening a flyout when a flyout is already open causes odd UX

### ISSUE THREAD

**Issue by Blackbaud-ColbyWhite** [blackbaud/skyux-flyout#99] opened 2020-09-14 14:42 UTC
### Expected behavior
If the flyout is open with content A and you try to open it with content B, the flyout remains open and the content is filled with B. (i have no strong opinions on how the transition from A to B should be handled, but a simple "lets just get it done" transition would be to close the flyout and immediately open it with B since that more closely mimics the existing actual behavior.

### Actual behavior
the flyout is closed and content B is never shown. user has to redo whatever action was supposed to bring up content B, causing for an odd user experience.

### Steps to reproduce
you can do this on the [flyout doc](https://developer.blackbaud.com/skyux/components/flyout#demo) page. j/ click around on the buttons and note you have to click twice in diff scenarios.

### Severity/Impact
The next version of the help widget will leverage this component heavily. today's implementation has a pretty bad user experience.

**Comment by Blackbaud-DanMiller** [comment] 2020-09-14 15:50
duplicate of #81

**Closed by Blackbaud-DanMiller** 2020-09-14 15:50 UTC
